<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-s can fix this:

1. **Set the `java.awt.headless` Property**:
   Add the `-Djava.awt.headless=true`urefire-plugin</artifactId>
  <version>3.0.0</version>
 property to your Maven command or Java options. This ensures that  <configuration>
    <argLine>-Djava.awt.headless=true</argLine all AWT operations are run in headless mode.

   Update your workflow file `.github/workflows>
  </configuration>
</plugin>



jobs:
  build:
    runsReview the failing test cases (`TestValidation` and `-on: ubuntu-latest
    steps:
    - name:MessageTest`) to ensure they are not relying on GUI-based Checkout code
      uses: actions/checkout@v3
    components. If these tests require a GUI, consider mocking - name: Set or refactoring the code to remove these dependencies.

up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '23#### 3. Alternative: Use a Virtual Display
If GUI operations are unavoidable, you can use a virtual display'
        distribution: 'temurin'
    - name: Build (like Xvfb) in the GitHub Actions workflow. with Maven
      run: mvn clean test -Djava.awt Update your workflow file (`.github/workflows/Credential.headless=true

        
         
